name: "snnlpnet"
markdown: redcarpet
highlighter: pygments
permalink: :title
github: [https://github.com/snnlpnet/snnlpnet.github.io]
exclude: [README.md, LICENSE, Makefile,nohup.out]

# Information for the Atom feed
gereksiz:
   author: "ssnlpnet"
   email: "snnlpnet@gmail.com"
