name: "snnlpnet"
markdown: redcarpet
highlighter: pygments
permalink: :title
exclude: [README.md, LICENSE, Makefile, nohup.out]
redcarpet:
  extensions:
    - fenced_code_blocks
    - no_intra_emphasis
    - strikethrough
    - autolink
    - tables
# Information for the Atom feed
gereksiz:
   author: "ssnlpnet"
   email: "snnlpnet@gmail.com"
