name: "Smallyoung"
markdown: redcarpet
highlighter: pygments
permalink: :title
exclude: [README.md, LICENSE, Makefile,nohup.out]

# Information for the Atom feed
gereksiz:
   author: "smallyoung"
   email: "kyleteng@outlook.com"
