name: "opensmt"
markdown: redcarpet
highlighter: pygments
permalink: :title
exclude: [README.md, LICENSE, Makefile, nohup.out]
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
  #extensions:
  #  - fenced_code_blocks
  #  - no_intra_emphasis
  #  - strikethrough
  #  - autolink
  #  - tables
  #  - with_toc_data
  #  - superscript
# extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
# Information for the Atom feed
gereksiz:
   author: "ssnlpnet"
   email: "snnlpnet@gmail.com"
comments: true
